export const adminCopy = {
  title: 'Admin',
  opcionesTitle: 'Opciones del menú',
  opcionesBody: 'Lo que ves acá es lo que el huésped ve en el Home y en el menú de abajo.',
  habilitada: 'Habilitada',
  deshabilitada: 'Deshabilitada',
  habilitar: 'Habilitar',
  deshabilitar: 'Deshabilitar',

  serviciosTitle: 'Servicios de Reservas',
  serviciosBody: 'Sauna y Cold Plunge siempre están. Acá se agregan otros servicios.',
  serviciosEmpty: 'Todavía no agregaste ningún servicio.',
  nuevoServicio: 'Agregar servicio',
  nombreLabel: 'Nombre',
  nombrePlaceholder: 'Ej.: Entrenamiento personal',
  descripcionLabel: 'Descripción',
  descripcionPlaceholder: 'Ej.: Sesión de entrenamiento personalizado.',
  proveedorLabel: 'Con quién',
  proveedorPlaceholder: 'Ej.: Alex Quesada',
  precioLabel: 'Precio (USD)',
  unidadLabel: 'Por',
  duracionLabel: 'Duración (minutos)',
  horaInicioLabel: 'Desde',
  horaFinLabel: 'Hasta',
  guardar: 'Guardar servicio',
  guardando: 'Guardando…',
  nombreRequerido: 'Escribí un nombre.',
  error: 'No se pudo guardar. Probá de nuevo.',
};
